#!/usr/bin/env python3
"""
Generate the TinyTapeout RTL from trained weights.

Writes three files into src/:

    backbone.v      frozen ternary weights, constant-folded into logic
    head.v          loadable ternary head, shifted in serially
    tt_um_*.v       top level: TT pins, image register, FSM

Also writes a bitstream for the trained head so the tests have something
real to load.

    python3 emit_rtl.py --npz weights_f56.npz --user yourgithubname
    python3 emit_rtl.py --npz weights_f56.npz --user yourgithubname --lanes 8

The generated files are outputs, never edited by hand. Rerun this whenever
the weights change.
"""

import argparse
import json
from pathlib import Path

import numpy as np

from emit_tests import emit_tb, emit_test_py

PIXELS = 64
ACC_W = 9
BIAS_W = 8


# ------------------------------------------------------------- backbone

def emit_backbone(W, biases, lanes):
    """One pixel per cycle from an on-chip image register, `lanes`
    accumulators reused across passes. Weights are constants, so +1 becomes
    a wire, -1 an inverter, and 0 disappears along with its adder input."""
    n_feat = W.shape[0]
    if n_feat % lanes:
        raise ValueError(f"{n_feat} features not divisible by {lanes} lanes")
    passes = n_feat // lanes
    pass_w = max(1, (passes - 1).bit_length())
    rom_len = PIXELS * (1 << pass_w)

    def blit(f):
        b = int(biases[f])
        return (f"-$signed({ACC_W}'sd{-b})" if b < 0
                else f"$signed({ACC_W}'sd{b})")

    def bmux(l):
        if passes == 1:
            return blit(l)
        return "".join(
            f"({pass_w}'d{p} == pnum_next) ? {blit(p*lanes+l)} : "
            for p in range(passes - 1)) + blit((passes - 1) * lanes + l)

    L = [
        "// GENERATED by emit_rtl.py -- do not edit",
        f"// {n_feat} features, {lanes} lanes, {passes} passes,"
        f" {(W == 0).mean():.1%} zero weights",
        "",
        "`default_nettype none",
        "",
        "module backbone (",
        "    input  wire clk,",
        "    input  wire rst_n,",
        "    input  wire start,",
        f"    input  wire [{PIXELS-1}:0] img,",
        f"    output reg  [{n_feat-1}:0] features,",
        "    output reg  done,",
        "    output wire busy_o",
        ");",
        "    reg [5:0] idx;",
        f"    reg [{pass_w-1}:0] pnum;",
        f"    wire [{pass_w-1}:0] pnum_next = pnum + {pass_w}'d1;",
        f"    wire [{pass_w+5}:0] rom = {{pnum, idx}};",
        "    reg busy;",
        "    assign busy_o = busy;",
        "    wire pix = img[idx];",
        "",
    ]

    for l in range(lanes):
        pos = ["0"] * rom_len
        neg = ["0"] * rom_len
        for p in range(passes):
            f = p * lanes + l
            for i in range(PIXELS):
                if W[f, i] == 1:
                    pos[p * PIXELS + i] = "1"
                elif W[f, i] == -1:
                    neg[p * PIXELS + i] = "1"
        L.append(f"    localparam [{rom_len-1}:0] POS{l} = "
                 f"{rom_len}'b{''.join(reversed(pos))};")
        L.append(f"    localparam [{rom_len-1}:0] NEG{l} = "
                 f"{rom_len}'b{''.join(reversed(neg))};")

    L.append("")
    for l in range(lanes):
        L.append(f"    reg signed [{ACC_W-1}:0] acc{l};")
    L.append("")
    for l in range(lanes):
        L.append(f"    wire signed [{ACC_W-1}:0] nxt{l} = acc{l}"
                 f" + ((pix & POS{l}[rom]) ? {ACC_W}'sd1 :"
                 f" (pix & NEG{l}[rom]) ? -{ACC_W}'sd1 : {ACC_W}'sd0);")

    L += [
        "",
        "    always @(posedge clk) begin",
        "        if (!rst_n) begin",
        "            idx <= 6'd0; pnum <= 0; busy <= 1'b0;",
        "            done <= 1'b0; features <= 0;",
    ]
    for l in range(lanes):
        L.append(f"            acc{l} <= {ACC_W}'sd0;")
    L += [
        "        end else if (start) begin",
        "            idx <= 6'd0; pnum <= 0; busy <= 1'b1; done <= 1'b0;",
    ]
    for l in range(lanes):
        L.append(f"            acc{l} <= {blit(l)};")
    L += [
        "        end else if (busy) begin",
        "            if (idx == 6'd63) begin",
        "                case (pnum)",
    ]
    for p in range(passes):
        L.append(f"                    {pass_w}'d{p}: begin")
        for l in range(lanes):
            L.append(f"                        features[{p*lanes+l}]"
                     f" <= ~nxt{l}[{ACC_W-1}];")
        L.append("                    end")
    L.append("                    default: ;")
    L.append("                endcase")
    for l in range(lanes):
        L.append(f"                acc{l} <= {bmux(l)};")
    L += [
        f"                if (pnum == {pass_w}'d{passes-1}) begin",
        "                    busy <= 1'b0; done <= 1'b1;",
        "                end else pnum <= pnum_next;",
        "                idx <= 6'd0;",
        "            end else begin",
    ]
    for l in range(lanes):
        L.append(f"                acc{l} <= nxt{l};")
    L += [
        "                idx <= idx + 6'd1;",
        "            end",
        "        end else done <= 1'b0;",
        "    end",
        "endmodule",
        "",
        "`default_nettype wire",
    ]
    return "\n".join(L) + "\n", passes


# ----------------------------------------------------------------- head

def emit_head(n_feat, n_class):
    n_w = n_feat * n_class
    bits = 2 * n_w + BIAS_W * n_class
    iw = max(1, (n_feat - 1).bit_length())
    cw = max(1, (max(n_class - 1, 1)).bit_length())
    return f"""// GENERATED by emit_rtl.py -- do not edit
// Loadable head: {n_w} ternary weights + {n_class} biases = {bits} bits
// ({(bits + 7) // 8} bytes). These are the only weights that can change.

`default_nettype none

module head (
    input  wire clk,
    input  wire rst_n,
    input  wire load_en,
    input  wire load_bit,
    input  wire start,
    input  wire [{n_feat-1}:0] features,
    output reg  signed [{BIAS_W-1}:0] score,
    output reg  score_valid,
    output reg  [{cw-1}:0] score_idx,
    output reg  busy
);
    localparam BITS = {bits};
    reg [BITS-1:0] wreg;

    always @(posedge clk) begin
        if (!rst_n)       wreg <= 0;
        else if (load_en) wreg <= {{wreg[BITS-2:0], load_bit}};
    end

    reg [{iw-1}:0] widx;
    reg [{cw-1}:0] cidx;
    reg signed [{BIAS_W-1}:0] acc;

    wire [1:0] wsel = wreg[2*(cidx*{n_feat} + widx) +: 2];
    wire fbit = features[widx];
    wire signed [{BIAS_W-1}:0] nxt =
        (fbit && wsel == 2'b01) ? acc + {BIAS_W}'sd1 :
        (fbit && wsel == 2'b10) ? acc - {BIAS_W}'sd1 : acc;

    always @(posedge clk) begin
        if (!rst_n) begin
            widx <= 0; cidx <= 0; acc <= 0; busy <= 1'b0;
            score <= 0; score_valid <= 1'b0; score_idx <= 0;
        end else if (start) begin
            widx <= 0; cidx <= 0; busy <= 1'b1; score_valid <= 1'b0;
            acc <= $signed(wreg[2*{n_w} +: {BIAS_W}]);
        end else if (busy) begin
            if (widx == {n_feat - 1}) begin
                widx <= 0;
                score <= nxt;
                score_idx <= cidx;
                score_valid <= 1'b1;
                if (cidx == {n_class - 1}) begin
                    busy <= 1'b0;
                end else begin
                    cidx <= cidx + 1;
                    acc <= $signed(wreg[2*{n_w} + {BIAS_W}*(cidx + 1) +: {BIAS_W}]);
                end
            end else begin
                widx <= widx + 1;
                acc <= nxt;
                score_valid <= 1'b0;
            end
        end else score_valid <= 1'b0;
    end
endmodule

`default_nettype wire
"""


# ------------------------------------------------------------------ top

def emit_top(module, n_feat, n_class, lanes, passes, bits):
    cw = max(1, (max(n_class - 1, 1)).bit_length())
    return f"""// GENERATED by emit_rtl.py -- do not edit
//
// Frozen ternary backbone + SPI-loadable classifier head.
//
//   64 pixels -> frozen {PIXELS}->{n_feat} layer (in logic) -> {n_feat} bits
//             -> loadable {n_feat}->{n_class} head ({bits} bits) -> {n_class} scores
//
// Pins
//   ui_in[0]  img_bit    pixel data
//   ui_in[1]  img_shift  shift one pixel in
//   ui_in[2]  go         start an inference
//   ui_in[3]  hd_bit     head bitstream data
//   ui_in[4]  hd_shift   shift one head bit in
//   uo_out    score      signed 8-bit, one class at a time
//   uio_out[0] score_valid
//   uio_out[1] done          all {n_class} scores emitted
//   uio_out[2] busy
//   uio_out[{2+cw+1}:3] score_idx  which class this score belongs to

`default_nettype none

module {module} (
    input  wire [7:0] ui_in,
    output wire [7:0] uo_out,
    input  wire [7:0] uio_in,
    output wire [7:0] uio_out,
    output wire [7:0] uio_oe,
    input  wire       ena,
    input  wire       clk,
    input  wire       rst_n
);
    wire img_bit   = ui_in[0];
    wire img_shift = ui_in[1];
    wire go        = ui_in[2];
    wire hd_bit    = ui_in[3];
    wire hd_shift  = ui_in[4];

    // image register: shift {PIXELS} pixels in, then hold them still while
    // the backbone makes {passes} passes over them
    reg [{PIXELS-1}:0] img;
    always @(posedge clk) begin
        if (!rst_n)        img <= 0;
        else if (img_shift) img <= {{img[{PIXELS-2}:0], img_bit}};
    end

    wire [{n_feat-1}:0] features;
    wire bb_done, bb_busy;

    backbone u_bb (
        .clk(clk), .rst_n(rst_n), .start(go), .img(img),
        .features(features), .done(bb_done), .busy_o(bb_busy)
    );

    // head starts automatically when the backbone finishes
    wire signed [{BIAS_W-1}:0] score;
    wire score_valid, hd_busy;
    wire [{cw-1}:0] score_idx;

    head u_hd (
        .clk(clk), .rst_n(rst_n),
        .load_en(hd_shift), .load_bit(hd_bit),
        .start(bb_done), .features(features),
        .score(score), .score_valid(score_valid),
        .score_idx(score_idx), .busy(hd_busy)
    );

    reg done;
    always @(posedge clk) begin
        if (!rst_n) done <= 1'b0;
        else if (go) done <= 1'b0;
        else if (score_valid && score_idx == {cw}'d{n_class-1}) done <= 1'b1;
    end

    assign uo_out  = score;
    assign uio_out = {{{{{8-3-cw}{{1'b0}}}}, score_idx, hd_busy | bb_busy,
                      done, score_valid}};
    assign uio_oe  = 8'hFF;

    wire _unused = &{{ena, uio_in, ui_in[7:5], 1'b0}};
endmodule

`default_nettype wire
"""


# ------------------------------------------------------------- bitstream

def pack_head(W2, b2, n_feat, n_class):
    """Pack head weights into the bitstream, MSB first.

    Layout matches the shift register: weight for (class c, feature f) sits
    at bit offset 2*(c*n_feat + f), biases follow.
    """
    n_w = n_feat * n_class
    bits = [0] * (2 * n_w + BIAS_W * n_class)
    for c in range(n_class):
        for f in range(n_feat):
            w = int(W2[c, f])
            code = {0: 0b00, 1: 0b01, -1: 0b10}[w]
            off = 2 * (c * n_feat + f)
            bits[off] = code & 1
            bits[off + 1] = (code >> 1) & 1
    for c in range(n_class):
        v = int(b2[c]) & 0xFF
        off = 2 * n_w + BIAS_W * c
        for k in range(BIAS_W):
            bits[off + k] = (v >> k) & 1
    # shifted in MSB first, so emit the top bit of the register first
    return "".join(str(b) for b in reversed(bits))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--npz", required=True)
    ap.add_argument("--user", required=True,
                    help="your GitHub username, lowercase")
    ap.add_argument("--lanes", type=int, default=8)
    ap.add_argument("--classes", type=int, default=6)
    ap.add_argument("--out", default="../src")
    ap.add_argument("--test-out", default="../test")
    ap.add_argument("--vectors", type=int, default=8)
    args = ap.parse_args()

    user = "".join(c for c in args.user.lower() if c.isalnum() or c == "_")
    module = f"tt_um_{user}_folded_nn"

    d = np.load(args.npz)
    W1 = d["W1"].astype(int)
    if W1.shape[1] != PIXELS:
        W1 = W1.T
    n_feat = W1.shape[0]
    b1 = d["b1"].astype(int) if "b1" in d else np.zeros(n_feat, int)

    W2 = d["W2"].astype(int)
    if W2.shape[1] != n_feat:
        W2 = W2.T
    b2 = d["b2"].astype(int) if "b2" in d else np.zeros(W2.shape[0], int)
    W2, b2 = W2[:args.classes], b2[:args.classes]

    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    bb, passes = emit_backbone(W1, b1, args.lanes)
    (out / "backbone.v").write_text(bb)
    (out / "head.v").write_text(emit_head(n_feat, args.classes))

    _bits = 2 * n_feat * args.classes + BIAS_W * args.classes
    (out / f"{module}.v").write_text(
        emit_top(module, n_feat, args.classes, args.lanes, passes, _bits))

    bits = 2 * n_feat * args.classes + BIAS_W * args.classes
    stream = pack_head(W2, b2, n_feat, args.classes)

    # test vectors from the numpy model
    rng = np.random.default_rng(11)
    imgs = (rng.random((args.vectors, PIXELS)) < 0.22).astype(int)
    feats = ((imgs @ W1.T + b1) >= 0).astype(int)
    scores = feats @ W2.T + b2
    vectors = [("".join(str(x) for x in reversed(im)), sc.tolist())
               for im, sc in zip(imgs, scores)]

    tdir = Path(args.test_out)
    tdir.mkdir(parents=True, exist_ok=True)
    (tdir / "tb.v").write_text(emit_tb(module))
    (tdir / "test.py").write_text(emit_test_py(
        args.classes, bits, stream, vectors,
        PIXELS * passes + n_feat * args.classes))
    meta = {
        "module": module, "features": n_feat, "classes": args.classes,
        "lanes": args.lanes, "passes": passes,
        "head_bits": bits, "head_bytes": (bits + 7) // 8,
        "backbone_cycles": PIXELS * passes,
        "head_cycles": n_feat * args.classes,
        "total_cycles": PIXELS * passes + n_feat * args.classes,
        "zero_rate": float((W1 == 0).mean()),
        "bitstream": stream,
    }
    Path("head_bitstream.json").write_text(json.dumps(meta, indent=2))

    print(f"wrote {out}/backbone.v, {out}/head.v, {out}/{module}.v")
    print(f"      {tdir}/tb.v, {tdir}/test.py")
    print(f"      head_bitstream.json\n")
    print(f"  module        {module}")
    print(f"  features      {n_feat}  ({args.lanes} lanes, {passes} passes)")
    print(f"  zero rate     {(W1 == 0).mean():.1%}")
    print(f"  head          {bits} bits = {(bits + 7) // 8} bytes")
    print(f"  cycles        {meta['total_cycles']} per inference")
    print(f"\ninfo.yaml:")
    print(f"  top_module: \"{module}\"")
    print(f"  source_files:")
    for f in ("backbone.v", "head.v", f"{module}.v"):
        print(f"    - \"{f}\"")


if __name__ == "__main__":
    main()
