"""Generates test/tb.v and test/test.py for the TinyTapeout project.

The cocotb test has its vectors baked in as literals, so CI needs no numpy,
no dataset, and no extra files.
"""

TB_TEMPLATE = """// GENERATED by emit_rtl.py -- do not edit
//
// Instantiates the design and exposes wires for the cocotb tests.
// Note: ihp-sg13g2 netlists have no VPWR/VGND ports, unlike sky130.

`default_nettype none
`timescale 1ns / 1ps

module tb ();

  initial begin
    $dumpfile("tb.fst");
    $dumpvars(0, tb);
    #1;
  end

  reg clk;
  reg rst_n;
  reg ena;
  reg [7:0] ui_in;
  reg [7:0] uio_in;
  wire [7:0] uo_out;
  wire [7:0] uio_out;
  wire [7:0] uio_oe;

  MODULE user_project (
      .ui_in  (ui_in),
      .uo_out (uo_out),
      .uio_in (uio_in),
      .uio_out(uio_out),
      .uio_oe (uio_oe),
      .ena    (ena),
      .clk    (clk),
      .rst_n  (rst_n)
  );

endmodule
"""

TEST_TEMPLATE = '''# GENERATED by emit_rtl.py -- do not edit
"""Checks the chip against vectors computed by the numpy model.

Per inference:
  1. shift NBITS head bits in, MSB first (once, unless retargeting)
  2. shift 64 pixels in, MSB first
  3. pulse start
  4. wait for done, collecting NCLASS scores

Synchronise on done. Never on a count of score pulses.
"""

import cocotb
from cocotb.clock import Clock
from cocotb.triggers import ClockCycles, RisingEdge

HEAD_BITS = "STREAM"
CYCLES = NCYCLES
NCLASS = NCLASSVAL

VECTORS = [
VECTORS_BODY
]


def _val(sig):
    """Read a signal, treating x/z as 0.

    Gate-level flip-flops start undefined and there is no initial block,
    so int(sig.value) can raise before reset has propagated.
    """
    return int(sig.value.binstr.lower().replace("x", "0").replace("z", "0"), 2)


def _pins(dut, img_bit=0, img_shift=0, go=0, hd_bit=0, hd_shift=0):
    dut.ui_in.value = ((img_bit & 1) | ((img_shift & 1) << 1) |
                       ((go & 1) << 2) | ((hd_bit & 1) << 3) |
                       ((hd_shift & 1) << 4))


async def reset(dut):
    dut.ena.value = 1
    dut.uio_in.value = 0
    _pins(dut)
    dut.rst_n.value = 0
    await ClockCycles(dut.clk, 5)
    dut.rst_n.value = 1
    await ClockCycles(dut.clk, 2)


async def load_head(dut):
    for b in HEAD_BITS:
        _pins(dut, hd_bit=int(b), hd_shift=1)
        await ClockCycles(dut.clk, 1)
    _pins(dut)
    await ClockCycles(dut.clk, 1)


async def classify(dut, img_bits):
    for b in img_bits:
        _pins(dut, img_bit=int(b), img_shift=1)
        await ClockCycles(dut.clk, 1)
    _pins(dut)
    await ClockCycles(dut.clk, 1)

    _pins(dut, go=1)
    await ClockCycles(dut.clk, 1)
    _pins(dut)

    scores = [None] * NCLASS
    for _ in range(CYCLES * 3):
        await RisingEdge(dut.clk)
        uio = _val(dut.uio_out)
        if uio & 1:
            idx = (uio >> 3) & 0x7
            raw = _val(dut.uo_out)
            scores[idx] = raw - 256 if raw > 127 else raw
        if (uio >> 1) & 1:
            break
    return scores


@cocotb.test()
async def test_inference(dut):
    """Every score must match the numpy model exactly."""
    cocotb.start_soon(Clock(dut.clk, 100, units="ns").start())
    await reset(dut)
    await load_head(dut)

    for n, (img, expect) in enumerate(VECTORS):
        got = await classify(dut, img)
        assert got == expect, f"image {n}: expected {expect}, got {got}"
    dut._log.info(f"{len(VECTORS)} images, all scores bit-exact")


@cocotb.test()
async def test_reload_head(dut):
    """Reloading the head must reproduce the same answers.

    This is the retargeting path: the frozen backbone never changes, only
    the head bits do.
    """
    cocotb.start_soon(Clock(dut.clk, 100, units="ns").start())
    await reset(dut)
    await load_head(dut)
    first = await classify(dut, VECTORS[0][0])

    await load_head(dut)
    second = await classify(dut, VECTORS[0][0])
    assert first == second, f"reload changed the result: {first} vs {second}"


@cocotb.test()
async def test_reset_midway(dut):
    """Reset partway through a load must not leave the chip stuck."""
    cocotb.start_soon(Clock(dut.clk, 100, units="ns").start())
    await reset(dut)
    for b in HEAD_BITS[:100]:
        _pins(dut, hd_bit=int(b), hd_shift=1)
        await ClockCycles(dut.clk, 1)

    await reset(dut)
    await load_head(dut)
    got = await classify(dut, VECTORS[0][0])
    assert got == VECTORS[0][1], f"after reset: expected {VECTORS[0][1]}, got {got}"
'''


def emit_tb(module):
    return TB_TEMPLATE.replace("MODULE", module)


def emit_test_py(n_class, bits, stream, vectors, cycles):
    body = ",\n".join(f'    ("{img}", {list(sc)})' for img, sc in vectors)
    return (
        TEST_TEMPLATE.replace("STREAM", stream)
        .replace("NCYCLES", str(cycles))
        .replace("NCLASSVAL", str(n_class))
        .replace("NBITS", str(bits))
        .replace("VECTORS_BODY", body)
    )
