// GENERATED by emit_rtl.py -- do not edit
// Loadable head: 336 ternary weights + 6 biases = 720 bits
// (90 bytes). These are the only weights that can change.

`default_nettype none

module head (
    input  wire clk,
    input  wire rst_n,
    input  wire load_en,
    input  wire load_bit,
    input  wire start,
    input  wire [55:0] features,
    output reg  signed [7:0] score,
    output reg  score_valid,
    output reg  [2:0] score_idx,
    output reg  busy
);
    localparam BITS = 720;
    reg [BITS-1:0] wreg;

    always @(posedge clk) begin
        if (!rst_n)       wreg <= 0;
        else if (load_en) wreg <= {wreg[BITS-2:0], load_bit};
    end

    reg [5:0] widx;
    reg [2:0] cidx;
    reg signed [7:0] acc;

    wire [1:0] wsel = wreg[2*(cidx*56 + widx) +: 2];
    wire fbit = features[widx];
    wire signed [7:0] nxt =
        (fbit && wsel == 2'b01) ? acc + 8'sd1 :
        (fbit && wsel == 2'b10) ? acc - 8'sd1 : acc;

    always @(posedge clk) begin
        if (!rst_n) begin
            widx <= 0; cidx <= 0; acc <= 0; busy <= 1'b0;
            score <= 0; score_valid <= 1'b0; score_idx <= 0;
        end else if (start) begin
            widx <= 0; cidx <= 0; busy <= 1'b1; score_valid <= 1'b0;
            acc <= $signed(wreg[2*336 +: 8]);
        end else if (busy) begin
            if (widx == 55) begin
                widx <= 0;
                score <= nxt;
                score_idx <= cidx;
                score_valid <= 1'b1;
                if (cidx == 5) begin
                    busy <= 1'b0;
                end else begin
                    cidx <= cidx + 1;
                    acc <= $signed(wreg[2*336 + 8*(cidx + 1) +: 8]);
                end
            end else begin
                widx <= widx + 1;
                acc <= nxt;
                score_valid <= 1'b0;
            end
        end else score_valid <= 1'b0;
    end
endmodule

`default_nettype wire
