// GENERATED by emit_rtl.py -- do not edit
//
// Frozen ternary backbone + SPI-loadable classifier head.
//
//   64 pixels -> frozen 64->56 layer (in logic) -> 56 bits
//             -> loadable 56->6 head (720 bits) -> 6 scores
//
// Pins
//   ui_in[0]  img_bit    pixel data
//   ui_in[1]  img_shift  shift one pixel in
//   ui_in[2]  go         start an inference
//   ui_in[3]  hd_bit     head bitstream data
//   ui_in[4]  hd_shift   shift one head bit in
//   uo_out    score      signed 8-bit, one class at a time
//   uio_out[0] score_valid
//   uio_out[1] done          all 6 scores emitted
//   uio_out[2] busy
//   uio_out[6:3] score_idx  which class this score belongs to

`default_nettype none

module tt_um_rahulmascarenhas_folded_nn (
    input  wire [7:0] ui_in,
    output wire [7:0] uo_out,
    input  wire [7:0] uio_in,
    output wire [7:0] uio_out,
    output wire [7:0] uio_oe,
    input  wire       ena,
    input  wire       clk,
    input  wire       rst_n
);
    wire img_bit   = ui_in[0];
    wire img_shift = ui_in[1];
    wire go        = ui_in[2];
    wire hd_bit    = ui_in[3];
    wire hd_shift  = ui_in[4];

    // image register: shift 64 pixels in, then hold them still while
    // the backbone makes 7 passes over them
    reg [63:0] img;
    always @(posedge clk) begin
        if (!rst_n)        img <= 0;
        else if (img_shift) img <= {img[62:0], img_bit};
    end

    wire [55:0] features;
    wire bb_done, bb_busy;

    backbone u_bb (
        .clk(clk), .rst_n(rst_n), .start(go), .img(img),
        .features(features), .done(bb_done), .busy_o(bb_busy)
    );

    // head starts automatically when the backbone finishes
    wire signed [7:0] score;
    wire score_valid, hd_busy;
    wire [2:0] score_idx;

    head u_hd (
        .clk(clk), .rst_n(rst_n),
        .load_en(hd_shift), .load_bit(hd_bit),
        .start(bb_done), .features(features),
        .score(score), .score_valid(score_valid),
        .score_idx(score_idx), .busy(hd_busy)
    );

    reg done;
    always @(posedge clk) begin
        if (!rst_n) done <= 1'b0;
        else if (go) done <= 1'b0;
        else if (score_valid && score_idx == 3'd5) done <= 1'b1;
    end

    assign uo_out  = score;
    assign uio_out = {{2{1'b0}}, score_idx, hd_busy | bb_busy,
                      done, score_valid};
    assign uio_oe  = 8'hFF;

    wire _unused = &{ena, uio_in, ui_in[7:5], 1'b0};
endmodule

`default_nettype wire
